"""
Script to generate AI videos using Magic Hour API.
This module handles the creation of AI-generated video content with audio.
"""
import os
import sys
import json
import requests
import time
from typing import Dict, List, Optional, TypedDict
from dotenv import load_dotenv

# Load environment variables
env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'secrets', '.env')
load_dotenv(env_path)

# Constants
TEMP_DIR = os.path.join(os.path.dirname(__file__), 'temporary_files')
API_URL = "https://api.magichour.ai/v1/text-to-video"

def get_next_clip_number() -> int:
    """
    Find the next available clip number by checking existing files.
    Returns the next number to use (1 if no files exist).
    """
    if not os.path.exists(TEMP_DIR):
        os.makedirs(TEMP_DIR)
        return 1
    
    existing_files = [f for f in os.listdir(TEMP_DIR) if f.startswith('clip_') and f.endswith('.mp4')]
    if not existing_files:
        return 1
    
    # Extract numbers from filenames and find the max
    numbers = []
    for file in existing_files:
        try:
            num = int(file.replace('clip_', '').replace('.mp4', ''))
            numbers.append(num)
        except ValueError:
            continue
    
    return max(numbers, default=0) + 1

def load_credentials() -> str:
    """Load Magic Hour API key from environment variables."""
    api_key = os.getenv('MAGIC_HOUR_API_KEY')
    if not api_key:
        raise Exception("Magic Hour API key not found in environment variables")
    return api_key

def get_video_status(video_id: str, headers: Dict[str, str]) -> Dict:
    """Check the status of a video generation request."""
    url = f"https://api.magichour.ai/v1/video-projects/{video_id}"
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    return response.json()

def generate_text_to_video(prompt: str) -> str:
    """
    Generate a video using Magic Hour's API and save it to temporary files.
    The video will be exactly 5 seconds long with audio (if generated by Magic Hour).
    
    Args:
        prompt: The exact prompt to use for video generation
    
    Returns:
        str: Path to the saved video file
    
    Raises:
        Exception: If video generation or download fails
    """
    api_key = load_credentials()
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    
    # Create video (no audio field; let the prompt drive sound design)
    payload = {
        "name": "Glass Apple Slice 9x16",
        "end_seconds": 5,
        "orientation": "portrait",
        "style": {
            "prompt": prompt,
            "quality_mode": "studio"
        }
    }
    
    try:
        print("Starting video generation...")
        print(f"Request payload: {json.dumps(payload, indent=2)}")
        response = requests.post(API_URL, json=payload, headers=headers)
        
        if not response.ok:
            print(f"Error response: {response.text}")
            print(f"Status code: {response.status_code}")
            response.raise_for_status()
            
        result = response.json()
        video_id = result["id"]
        print(f"Video job created, ID: {video_id}")
        
        # Poll for completion
        while True:
            status = get_video_status(video_id, headers)
            current_status = status.get('status')
            
            if current_status == 'complete':
                downloads = status.get('downloads', [])
                if not downloads:
                    print(f"Status data when complete: {json.dumps(status, indent=2)}")
                    raise Exception("Video complete but no downloads available")
                
                video_url = downloads[0].get('url')
                if not video_url:
                    print(f"Downloads data: {json.dumps(downloads, indent=2)}")
                    raise Exception("Video complete but no URL in downloads")
                
                clip_num = get_next_clip_number()
                output_path = os.path.join(TEMP_DIR, f'clip_{clip_num}.mp4')
                
                print(f"Downloading video from {video_url} to {output_path}")
                with requests.get(video_url, stream=True) as r:
                    r.raise_for_status()
                    with open(output_path, 'wb') as f:
                        for chunk in r.iter_content(chunk_size=8192):
                            f.write(chunk)
                
                print(f"Successfully downloaded video to {output_path}")
                return output_path
            
            elif current_status == 'failed':
                error_msg = status.get('error', 'Unknown error')
                print(f"Full error response: {json.dumps(status, indent=2)}")
                raise Exception(f"Video generation failed: {error_msg}")
            
            print(f"Video still processing... (status: {current_status})")
            time.sleep(10)
            
    except requests.exceptions.RequestException as e:
        print(f"Error generating video: {str(e)}")
        if hasattr(e, 'response') and e.response is not None:
            print(f"Full error response: {e.response.text}")
        raise
    except Exception as e:
        print(f"Error generating video: {str(e)}")
        raise

def main():
    """Main function to handle video generation process."""
    try:
        prompt = (
            "A cinematic, vertical close-up of a realistic hand slicing a translucent glass apple "
            "on a wooden cutting board. Sharp, crisp sound of the glass cracking as the knife cuts through, "
            "followed by a satisfying, soft tap when the apple slice lands on the board. Realistic textures, "
            "slow-motion, high detail. Emphasize the sound design: glass crack and gentle impact."
        )
        video_path = generate_text_to_video(prompt)
        print(f"Video saved to: {video_path}")
    except Exception as e:
        print(f"Failed to generate video: {str(e)}")

if __name__ == "__main__":
    main() 